import React, { useState, useMemo, useCallback } from 'react';
import { ShoppingItem, Supermarket, SortKey, SortDirection, AppView } from './src/types';
import { SessionContextProvider, useSession } from './src/components/SessionContextProvider';
import { useShoppingItems } from './src/hooks/useShoppingItems';
import Header from './src/components/Header';
import AddItemForm from './src/components/AddItemForm';
import ShoppingList from './src/components/ShoppingList';
import Totals from './src/components/Totals';
import Actions from './src/components/Actions';
import SortControl from './src/components/SortControl';
import AnalysisSection from './src/components/AnalysisSection';
import Login from './src/pages/Login';
import About from './src/pages/About';
import { SUPERMARKETS } from './src/constants';
import { supabase } from './src/integrations/supabase/client';
import { showError } from './src/utils/toast';

// --- Main Application Content Component ---
const AppContent: React.FC = () => {
  const { user } = useSession();
  const { items, isLoading: isItemsLoading, addItem, updateItem, removeItem, clearList } = useShoppingItems();
  const [sortKey, setSortKey] = useState<SortKey>('none');
  const [sortDirection, setSortDirection] = useState<SortDirection>('asc');
  const [currentView, setCurrentView] = useState<AppView>('list');

  const handleLogout = useCallback(async () => {
    const { error } = await supabase.auth.signOut();
    if (error) {
      showError('Erro ao sair: ' + error.message);
    }
  }, []);

  const handleAddItem = useCallback((item: Omit<ShoppingItem, 'id'>) => {
    // ID is generated by Supabase, but we need to pass the item structure
    addItem(item);
  }, [addItem]);

  const handleRemoveItem = useCallback((id: string) => {
    removeItem(id);
  }, [removeItem]);
  
  const handleUpdateItem = useCallback((updatedItem: ShoppingItem) => {
    updateItem(updatedItem);
  }, [updateItem]);

  const handleClearList = useCallback(() => {
    if (window.confirm('Tem certeza que deseja limpar a lista inteira? Esta ação é irreversível.')) {
      clearList();
    }
  }, [clearList]);

  const handleSortChange = useCallback((key: SortKey) => {
    setSortKey(prevKey => {
      if (prevKey === key) {
        // Toggle direction if the same key is clicked
        setSortDirection(prevDir => (prevDir === 'asc' ? 'desc' : 'asc'));
        return key;
      } else {
        // Reset direction to asc if a new key is selected
        setSortDirection('asc');
        return key;
      }
    });
  }, []);

  const sortedItems = useMemo(() => {
    if (sortKey === 'none') {
      return items;
    }

    const sorted = [...items].sort((a, b) => {
      // Ensure we are comparing strings for name and category
      const aValue = a[sortKey].toString().toLowerCase();
      const bValue = b[sortKey].toString().toLowerCase();

      if (aValue < bValue) return sortDirection === 'asc' ? -1 : 1;
      if (aValue > bValue) return sortDirection === 'asc' ? 1 : -1;
      return 0;
    });

    return sorted;
  }, [items, sortKey, sortDirection]);

  const totals = useMemo(() => {
    const initialTotals = Object.keys(SUPERMARKETS).reduce((acc, key) => {
      acc[key as Supermarket] = 0;
      return acc;
    }, {} as Record<Supermarket, number>);

    const marketTotals = items.reduce((acc, item) => {
      acc.iquegami += (item.prices.iquegami || 0) * item.quantity;
      acc.proenca += (item.prices.proenca || 0) * item.quantity;
      acc.max += (item.prices.max || 0) * item.quantity;
      return acc;
    }, initialTotals);

    const optimizedTotal = items.reduce((sum, item) => {
      // Fix: Explicitly cast Object.values to number[]
      const validPrices = (Object.values(item.prices) as number[]).filter(p => p > 0);
      const minPrice = validPrices.length > 0 ? Math.min(...validPrices) : 0;
      return sum + minPrice * item.quantity;
    }, 0);

    return { ...marketTotals, optimized: optimizedTotal };
  }, [items]);

  const renderMainContent = () => {
    if (isItemsLoading) {
        return (
            <div className="lg:col-span-2 bg-white p-6 rounded-lg shadow-md text-center py-16">
                <p className="text-lg text-brand-primary">Carregando sua lista...</p>
            </div>
        );
    }

    if (currentView === 'analysis') {
      return <AnalysisSection items={items} />;
    }
    
    if (currentView === 'about') {
        return <About />;
    }

    // Default view: 'list'
    return (
      <>
        {items.length > 0 && (
            <div className="mb-4">
                <SortControl 
                    sortKey={sortKey} 
                    sortDirection={sortDirection} 
                    onSortChange={handleSortChange} 
                />
            </div>
        )}
        <ShoppingList 
          items={sortedItems} 
          onRemoveItem={handleRemoveItem}
          onUpdateItem={handleUpdateItem} 
        />
         {items.length === 0 && (
            <div className="text-center py-16 px-6 bg-white rounded-lg shadow-md">
                <p className="text-gray-500">Sua lista de compras está vazia.</p>
                <p className="text-gray-400 mt-2">Use o formulário para adicionar seu primeiro item!</p>
            </div>
        )}
      </>
    );
  };

  return (
    <div className="min-h-screen bg-gray-50 text-brand-dark">
      <Header 
        currentView={currentView} 
        onViewChange={setCurrentView} 
        user={user}
        onLogout={handleLogout}
      />
      <main className="container mx-auto p-4 md:p-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            {renderMainContent()}
          </div>
          <div className="space-y-8">
            {currentView === 'list' && (
              <>
                <AddItemForm onAddItem={handleAddItem} />
                {items.length > 0 && <Totals totals={totals} />}
                <Actions 
                  items={items} 
                  onClearList={handleClearList} 
                  totalOptimized={totals.optimized} // Pass optimized total
                />
              </>
            )}
            {currentView !== 'list' && (
              <div className="bg-white p-6 rounded-lg shadow-md text-center text-gray-500">
                <p>Os painéis de Ações e Totais estão disponíveis apenas na visualização "Lista de Compras".</p>
              </div>
            )}
          </div>
        </div>
      </main>
      <footer className="text-center p-4 text-gray-500 text-sm">
        <p>&copy; {new Date().getFullYear()} Comparador de Compras Olímpia. Feito para facilitar suas compras.</p>
      </footer>
    </div>
  );
};

// --- Root Component with Auth Gate ---
const App: React.FC = () => {
  const { session, isLoading } = useSession();

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-brand-light">
        <p className="text-xl text-brand-primary">Carregando autenticação...</p>
      </div>
    );
  }

  if (!session) {
    return <Login />;
  }

  return <AppContent />;
};

// --- Root Wrapper ---
const RootApp: React.FC = () => (
    <SessionContextProvider>
        <App />
    </SessionContextProvider>
);

export default RootApp;